In [1]:
import h5py
import numpy as np
f = h5py.File('C:/Users/zuohaonan/Desktop/graduation_design/Codes/param.h5','r')

query = [data.decode('utf-8') for data in f['query_array']]
key = [data.decode('utf-8') for data in f['key_array']]

q_scale_factor = [data.decode('utf-8') for data in f['Q_factor_array']]
k_scale_factor = [data.decode('utf-8') for data in f['K_factor_array']]
s_scale_factor = [data.decode('utf-8') for data in f['S_factor_array']]
    
print("Q值：\n%s\n" % query)
print("K值：\n%s\n" % key)

print("Q缩放因子：\n%s\n" % q_scale_factor)
print("K缩放因子：\n%s\n" % k_scale_factor)
print("S缩放因子：\n%s\n" % s_scale_factor)

AttributeError: 'numpy.int64' object has no attribute 'decode'

In [8]:
import h5py
import numpy as np
##f = h5py.File('/Users/zuohaonan/Desktop/CNN/python/minst_CNN_weights2.h5','r')
##t = h5py.File('/Users/zuohaonan/Desktop/CNN/python/data_test2.h5','r')

kernel = [data.decode('utf-8') for data in f['kernel_weights']]
bias = [data.decode('utf-8') for data in f['bias']]
# pool_weight = [data.decode('utf-8') for data in f['pool_weights']]
# pool_bias = [data.decode('utf-8') for data in f['pool_bias']]
    
test_data = [data.decode('utf-8') for data in t['in_data']]

source = open('C:\\Users\\zuohaonan\\Desktop\\PE1\\NN_accelerator\\source_CNN01.txt','w')
##print('memory_initialization_radix=16;\nmemory_initialization_vector=', file=source)
pe_id = '0000000000000001'

s = '00' + '00000000000000001' + '1000000' + '1111111'+'1111111111111000'
print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,25):
    for j in range(0,8):
        s = '00' + pe_id + '1000000' + '{:0>7b}'.format(j+1) + kernel[i+25*j]
        print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,8):
    s = '00' + pe_id + '1000000' + '1000001' + bias[i][24:40]
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    s = '00' + pe_id + '1000000' + '1000010' + bias[i][8:24]
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    s = '00' + pe_id + '1000000' + '1000011' +  '00000000' + bias[i][0:8]
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# for i in range(0,6):
#     s = '00' + pe_id + '10000000' + '010100' + pool_weight[i]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# for i in range(0,6):
#     s = '00' + pe_id + '10000000' + '010101' + pool_bias[i][24:40]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#     s = '00' + pe_id + '10000000' + '010110' + pool_bias[i][8:24]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#     s = '00' + pe_id + '10000000' + '010111' + '00000000' + pool_bias[i][0:8]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# s = '00' + pe_id + '10000000' + '011010' + '00000000000000'+'11'
# print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#for i in range(0,56):
#    s = '00' + pe_id + '10000000' + '011011' + '10000'+'{:0>11b}'.format(i)
#    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#    s = '00' + pe_id + '10000000' + '011100' + '000000'+'0000000000'
#    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#s = '00' + pe_id + '10000000' + '011000' + '1101100000001000'
#print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#s = '00' + pe_id + '10000000' + '011001' + '0000000100100000'
#print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,1024):
    s = '00' + pe_id + '000' + '{:0>11b}'.format(i) + (test_data[i])
    print(s)
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,32):##输入补0
    s = '00' + pe_id + '000' + '{:0>11b}'.format(i+1024) + '{:0>16b}'.format(0)
    print(s)
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    
kernel_convert = list(map(trans, kernel))
ker = np.zeros((8, 25), dtype=np.int16)

for i in range(0,25):
    for j in range(0,8):
        ker[j][i] = kernel_convert[i + 25 * j]

for k in range(0,6):
    Core [k] = ker[k].reshape(5,5)
    print(f"这是第{k}个卷积核:")
    print(Core[k])
    

000000000000000001000000000000001111111111111110
000000000000000001000000000000011111111111111111
000000000000000001000000000000100000000000000110
000000000000000001000000000000110000000000000000
000000000000000001000000000001000000000000000110
000000000000000001000000000001011111111111111011
000000000000000001000000000001101111111111111001
000000000000000001000000000001110000000000000010
000000000000000001000000000010001111111111111100
000000000000000001000000000010010000000000000100
000000000000000001000000000010100000000000000111
000000000000000001000000000010110000000000000110
000000000000000001000000000011000000000000000100
000000000000000001000000000011011111111111111001
000000000000000001000000000011101111111111111111
000000000000000001000000000011110000000000000010
000000000000000001000000000100000000000000000101
000000000000000001000000000100011111111111111101
000000000000000001000000000100101111111111111111
000000000000000001000000000100110000000000000110
00000000000000000100

In [5]:
import numpy as np
import pandas as pd

#中位数为26
def trans(str):
    num = int(str, 2)

    if num > 32767:
        # 负数，计算补码
        value =num-65536
    else:
        value = num
    return value

def trans40(str):
    num = int(str, 2)

    if num > 549755813887:
        # 负数，计算补码
        value =num-1099511627776
    else:
        value = num
    return value

def binary_to_decimal(number):

    if number > 32767:
        # 负数，计算补码
        value =number-65536
    else:
        value = number
    return value

def cut_sobel(dacc, bit):
    mask = (1 << (bit-15)) - 1  # 0b11111111111111111111111111

    temp_bits = (dacc >> 15) & mask  # 获取27-40位
    dacc_40 = (dacc >> (bit-1)) & 1  # 获取最高位
    dacc_li = dacc & ((1 << 15) - 1)  # 获取0-14位

    if temp_bits == 0 or temp_bits == (1 << (bit-15)) - 1:
        dcut = (dacc_40 << 15) | dacc_li
    else:
        dcut = 0b1000000000000000 if dacc_40 else 0b0111111111111111
    return (binary_to_decimal(dcut))



test_data_convert = list(map(trans, test_data))
test_data_np = np.array(test_data_convert)
IFM = test_data_np.reshape(32,32)##IFM是原输入图




print('原输入特征图：')
print(IFM)


init = np.zeros((34, 34), dtype=int)
post = np.zeros((32, 32), dtype=int)##转换后的输入图
x_arr = np.zeros((32, 32), dtype=int)##转换后的输入图
y_arr = np.zeros((32, 32), dtype=int)##转换后的输入图

for i in range(1,33):
    for j in range(1,33):
        init[i][j] = IFM[i-1][j-1]

for i in range(0,34):
    init[0][i] = 0
    init[33][i] = 0

for i in range(0,34):
    init[i][0] = 0;
    init[i][33] = 0;


count= 0
threshold = 24

for i in range(0,32):
    for j in range(0,32):
        x_temp = -init[i][j]-2*init[i+1][j]-init[i+2][j]+init[i][j+2]+2*init[i+1][j+2]+init[i+2][j+2]
        y_temp = init[i][j] + 2 * init[i][j+1] + init[i][j+2] - init[i+2][j] - 2 * init[i + 2][j + 1] - init[i + 2][j + 2]
        x = cut_sobel(x_temp,19)
        y = cut_sobel(y_temp,19)
        x_arr[i][j] = x
        y_arr[i][j] = y
        resolve = (x if x >=0 else -x)+(y if y >=0 else -y)
        data_temp = resolve
        data = cut_sobel(data_temp,17)
        post[i][j] = data if (data>threshold) else 0
        if post[i][j] == 0:
            count+=1



print('这是中间过程x')
print(x_arr)
print('这是中间过程y')
print(y_arr)
print('处理后的输入特征图：')
print(post)



#channel_df = pd.DataFrame(post)  # 转换为 DataFrame
#channel_df.to_excel('C:\\Users\\zuohaonan\\Desktop\PE1\\NN_accelerator\\sobel1.xlsx', index=False)

global_median = np.median(post)
print(f"全局中位数: {global_median}")

print('稀疏度：')
print(count/(32*32))

kernel_convert = list(map(trans, kernel))
ker = np.zeros((8, 25), dtype=np.int16)
Core = [np.zeros((5, 5), dtype=int) for _ in range(8)]

bias_convert = list(map(trans40, bias))
# pool_weight_convert = list(map(trans, pool_weight))
# pool_bias_convert = list(map(trans40, pool_bias))
print('偏置:')
print(bias_convert)
# print('池化权重:')
# print(pool_weight_convert)
# print('池化偏置:')
# print(pool_bias_convert)

for i in range(0,25):
    for j in range(0,8):
        ker[j][i] = kernel_convert[i + 25 * j]
        
for k in range(0,8):
    Core [k] = ker[k].reshape(5,5)
    print(f"这是第{k}个卷积核:")
    print(Core[k])

post_MAC = [np.zeros((28, 28), dtype=int) for _ in range(8)]
mem = [np.zeros((28, 28), dtype=int) for _ in range(8)]
OFM = [np.zeros((14, 14), dtype=int) for _ in range(8)]

def conv(row_loc,col_loc,num):
    result = 0
    for i in range(0,5):
        for j in range(0,5):
            result += (Core[num])[i][j]*post[row_loc+i][col_loc+j]

    mem[num][row_loc][col_loc] = result
    result += int(bias_convert[num])

    if result < 0:
        result = 0
            
    return result

def cut(dacc,bit):

    mask= (1 << (26-bit)) - 1  # 0b11111111111111111111111111
    
    temp_bits = (dacc>> (bit+15)) & mask#获取27-40位
    dacc_40 = (dacc >> 40) & 1#获取最高位
    dacc_li = (dacc>>bit) & ((1 << 15) - 1)#获取0-14位

    if temp_bits == 0 or temp_bits == (1 << (26-bit)) - 1:
        dcut = (dacc_40 << 15) | dacc_li
    else:
        dcut = 0b1000000000000000 if dacc_40 else 0b0111111111111111
    return (binary_to_decimal(dcut))

def max(a,b,c,d):
    if(a>=b):
        t1 = a
    else:
        t1 = b

    if(c>=d):
        t2 = c
    else:
        t2 = d

    if(t1>=t2):
        return t1
    else:
        return t2
        
def pool(row_loc,col_loc,num):
      
    result = max((post_MAC[num])[2*row_loc][2*col_loc],(post_MAC[num])[2*row_loc+1][2*col_loc],(post_MAC[num])[2*row_loc][2*col_loc+1],(post_MAC[num])[2*row_loc+1][2*col_loc+1])
    return result

for i in range(0,28):
    for j in range(0,28):
        for k in range(0,8):
            temp = conv(i,j,k)
            post_MAC[k][i][j] = cut(int(temp),0)

for k in range(0,8):
    print(f'这是第{k}张中间结果')
    print(mem[k])
    print('\n')

data = []
for channel in range(0,8):  # 遍历每个通道
    channel_data = mem[channel]  # 获取当前通道的数据
    channel_df = pd.DataFrame(channel_data)  # 转换为 DataFrame
    channel_df['Channel'] = f'Channel {channel + 1}'  # 添加通道标识列
    data.append(channel_df)

# 将所有通道的数据合并成一个大的 DataFrame
combined_df = pd.concat(data, ignore_index=True)

# 将 DataFrame 写入 Excel 文件
combined_df.to_excel('C:\\Users\\zuohaonan\\Desktop\\PE1\\NN_accelerator\\middle.xlsx', index=False)
    
for i in range(0,14):
    for j in range(0,14):
        for k in range(0,8):
            OFM[k][i][j] = pool(i,j,k)

result1 = np.full(1568, "0000000000000000", dtype='U16')

all_values = np.concatenate([arr.flatten() for arr in OFM])
non_zero_values = all_values[all_values != 0]  # 过滤非零值

# 计算统计值（包括全体的最大值和最小值）
max_value = np.max(all_values)  # 包含零的最大值
min_value = np.min(all_values)  # 包含零的最小值

# 计算非零值的平均值和中位数
if len(non_zero_values) > 0:
    mean_non_zero = np.mean(non_zero_values)
    median_non_zero = np.median(non_zero_values)
else:
    mean_non_zero = 0  # 如果无非零值，默认输出0
    median_non_zero = 0

# 输出结果
print(f"最大值（含零）: {max_value}")
print(f"最小值（含零）: {min_value}")
print(f"非零值的平均值: {mean_non_zero}")
print(f"非零值的中位数: {median_non_zero}")
limit = round(mean_non_zero/16)



with open('C:\\Users\\zuohaonan\\Desktop\\PE1\\NN_accelerator\\ofm_data01.txt', 'w') as file:
    for k in range(0,8):
        print(f'这是第{k}张输出图')
        print(OFM[k])
        print('\n')
        for i in range(0,14):
            for j in range(0,14):
                if OFM[k][i][j] < 0:
                    value = OFM[k][i][j] + 65536
                else:
                    value = OFM[k][i][j]
                        
                hex_value = format(value, '04X')
                file.write(hex_value + '\n')


with h5py.File('C:\\Users\\zuohaonan\\Desktop\\PE1\\NN_accelerator\\result1t31.h5', 'w') as hf:
    result1 = hf.create_dataset("result", 
                               shape=(1568,), 
                               dtype=h5py.string_dtype(encoding='utf-8', length=16))
    
    index = 0
    for i in range(14):
        for j in range(14):
            for k in range(8):
                value = OFM[k][i][j]
                if value > (limit + 1):
                    value = int(value/limit)
                binary_str = format(value, '016b')
                result1[index] = binary_str
                index += 1


print("已写入完毕")


原输入特征图：
[[-2 -1  6 ... -7  1  3]
 [-3  1  5 ...  1 -4 -8]
 [-8  7  4 ... -5 -6  4]
 ...
 [-3 -8  5 ... -8 -7 -2]
 [ 2  4 -4 ... -5  1 -5]
 [ 7 -7 -5 ... -2  4 -6]]
这是中间过程x
[[ -1  24   6 ... -20  11   2]
 [  8  36   6 ... -35   1  13]
 [ 16  35   4 ... -40  -3  22]
 ...
 [ -8   8   3 ... -29  15  16]
 [ -7 -16   9 ... -11   2   1]
 [-10 -30  12 ...  -1  -8  -9]]
这是中间过程y
[[  5  -4 -16 ...  -4  15  20]
 [  4  -8  -8 ...   5  11   5]
 [  2   7  10 ...  -8  -5  -4]
 ...
 [-14 -10  -9 ...  11   5  12]
 [-21  -2  15 ... -25 -24  -3]
 [  8   6   0 ...  -7  -8  -9]]
处理后的输入特征图：
[[ 0 28  0 ...  0 26  0]
 [ 0 44  0 ... 40  0  0]
 [ 0 42  0 ... 48  0 26]
 ...
 [ 0  0  0 ... 40  0 28]
 [28  0  0 ... 36 26  0]
 [ 0 36  0 ...  0  0  0]]
全局中位数: 0.0
稀疏度：
0.546875
偏置:
[-6, 7, 0, 3, 9, 15, 13, -10]
这是第0个卷积核:
[[-8  1  4  1 -5]
 [ 0  0 -2 -6 -8]
 [-2  1 -3 -5  5]
 [-7  2  1 -6  4]
 [-5 -2  7 -5 -3]]
这是第1个卷积核:
[[ 5 -1 -5 -5 -6]
 [-4  0 -5 -3  7]
 [ 3 -3  1 -8 -4]
 [-4  6  3 -8  2]
 [ 4  3 -3  2 -5]]
这是第2个卷积核