In [1]:
import h5py
import numpy as np
f = h5py.File('C:/Users/zuohaonan/Desktop/PE3/NN_accelerator/minst_CNN_weights03t2.h5','r')
#t = h5py.File('C:/Users/zuohaonan/Desktop/PE3/NN_accelerator/data_test03.h5','r')
t = h5py.File('C:\\Users\\zuohaonan\\Desktop\\PE2\\NN_accelerator\\resultl2t3.h5','r')

kernel = [data.decode('utf-8') for data in f['kernel_weights']]
bias = [data.decode('utf-8') for data in f['bias']]
# pool_weight = [data.decode('utf-8') for data in f['pool_weights']]
# pool_bias = [data.decode('utf-8') for data in f['pool_bias']]
    
test_data = [data.decode('utf-8') for data in t['result']]

print("卷积核权重：\n%s\n" % kernel)
print("六个偏置：\n%s\n" % bias)
# print("六个池化权重：\n%s\n" % pool_weight)
# print("六个池化偏置：\n%s\n" % pool_bias)
print("输入数据：\n%s\n" % test_data)

卷积核权重：
['0000000000000110', '0000000000000101', '1111111111111000', '1111111111111101', '0000000000000111', '1111111111111111', '0000000000000001', '1111111111111000', '0000000000000101', '1111111111111010', '1111111111111110', '1111111111111000', '0000000000000111', '1111111111111001', '0000000000000111', '0000000000000010', '1111111111111111', '0000000000000001', '0000000000000010', '1111111111111001', '0000000000000101', '1111111111111011', '1111111111111001', '0000000000000110', '0000000000000100', '1111111111111101', '0000000000000001', '1111111111111101', '0000000000000001', '0000000000000101', '0000000000000101', '0000000000000010', '1111111111111110', '1111111111111101', '0000000000000101', '0000000000000011', '1111111111111011', '0000000000000110', '0000000000000110', '1111111111111000', '1111111111111011', '0000000000000110', '0000000000000110', '0000000000000001', '1111111111111001', '0000000000000110', '0000000000000101', '0000000000000100', '0000000000000001', '11111111111

In [13]:
import h5py
import numpy as np
##f = h5py.File('/Users/zuohaonan/Desktop/CNN/python/minst_CNN_weights2.h5','r')
##t = h5py.File('/Users/zuohaonan/Desktop/CNN/python/data_test2.h5','r')

kernel = [data.decode('utf-8') for data in f['kernel_weights']]
bias = [data.decode('utf-8') for data in f['bias']]
# pool_weight = [data.decode('utf-8') for data in f['pool_weights']]
# pool_bias = [data.decode('utf-8') for data in f['pool_bias']]
    
test_data = [data.decode('utf-8') for data in t['result']]

source = open('C:/Users/zuohaonan/Desktop/PE3_new/PE2/NN_accelerator/source_CNN03.txt','w')
#print('memory_initialization_radix=16;\nmemory_initialization_vector=', file=source)
pe_id = '0000000000000001'

s = '00' + '00000000000000001' + '1000000' + '1111111'+'1111111111111000'
print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,288):
    for j in range(0,32):##不同卷积核相同位置的参数排在一起
        s = '00' + pe_id + '1000000' + '{:0>7b}'.format(j+1) + kernel[i+288*j]
        print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,32):
    s = '00' + pe_id + '1000000' + '1000001' + bias[i][24:40]
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    #s = '00' + pe_id + '1000000' + '1000010' + bias[i][8:24]
    #print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    #s = '00' + pe_id + '1000000' + '1000011' +  '00000000' + bias[i][0:8]
    #print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# for i in range(0,6):
#     s = '00' + pe_id + '10000000' + '010100' + pool_weight[i]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# for i in range(0,6):
#     s = '00' + pe_id + '10000000' + '010101' + pool_bias[i][24:40]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#     s = '00' + pe_id + '10000000' + '010110' + pool_bias[i][8:24]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#     s = '00' + pe_id + '10000000' + '010111' + '00000000' + pool_bias[i][0:8]
#     print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

# s = '00' + pe_id + '10000000' + '011010' + '00000000000000'+'11'
# print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#for i in range(0,56):
#    s = '00' + pe_id + '10000000' + '011011' + '10000'+'{:0>11b}'.format(i)
#    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#    s = '00' + pe_id + '10000000' + '011100' + '000000'+'0000000000'
#    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

#s = '00' + pe_id + '10000000' + '011000' + '1101100000001000'
#print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
#s = '00' + pe_id + '10000000' + '011001' + '0000000100100000'
#print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,800):
    s = '00' + pe_id + '000' + '{:0>11b}'.format(i) + (test_data[i])
    print(s)
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)

for i in range(0,160):##输入补0
    s = '00' + pe_id + '000' + '{:0>11b}'.format(i+800) + '{:0>16b}'.format(0)
    print(s)
    print('{:0>12}'.format(hex(int(s, 2))[2:]), file=source)
    
#kernel_convert = list(map(trans, kernel))
#ker = np.zeros((32, 200), dtype=np.int16)

#for i in range(0,200):
#    for j in range(0,32):
#        ker[j][i] = kernel_convert[i + 200 * j]
    

000000000000000001000000000000000000000000000000
000000000000000001000000000000010000000000001000
000000000000000001000000000000100000000000000000
000000000000000001000000000000110000000000000000
000000000000000001000000000001000000000000000000
000000000000000001000000000001010000000000000000
000000000000000001000000000001100000000000000000
000000000000000001000000000001110000000000000000
000000000000000001000000000010000000000000000000
000000000000000001000000000010010000000000000000
000000000000000001000000000010100000000000000000
000000000000000001000000000010110000000000001010
000000000000000001000000000011000000000000000000
000000000000000001000000000011010000000000101000
000000000000000001000000000011100000000000000000
000000000000000001000000000011110000000000000000
000000000000000001000000000100000000000000000000
000000000000000001000000000100010000000000001000
000000000000000001000000000100100000000000000000
000000000000000001000000000100110000000000010110
00000000000000000100

In [14]:
import numpy as np
import pandas as pd
#中位数为26
def trans(str):
    num = int(str, 2)

    if num > 32767:
        # 负数，计算补码
        value =num-65536
    else:
        value = num
    return value

def trans40(str):
    num = int(str, 2)

    if num > 549755813887:
        # 负数，计算补码
        value =num-1099511627776
    else:
        value = num
    return value

def binary_to_decimal(number):

    if number > 32767:
        # 负数，计算补码
        value =number-65536
    else:
        value = number
    return value

def cut_sobel(dacc, bit):
    mask = (1 << (bit-15)) - 1  # 0b11111111111111111111111111

    temp_bits = (dacc >> 15) & mask  # 获取27-40位
    dacc_40 = (dacc >> (bit-1)) & 1  # 获取最高位
    dacc_li = dacc & ((1 << 15) - 1)  # 获取0-14位

    if temp_bits == 0 or temp_bits == (1 << (bit-15)) - 1:
        dcut = (dacc_40 << 15) | dacc_li
    else:
        dcut = 0b1000000000000000 if dacc_40 else 0b0111111111111111
    return (binary_to_decimal(dcut))

test_data_convert = list(map(trans, test_data))
test_data_np = np.array(test_data_convert)
IFM = test_data_np.reshape(5,5,32)##IFM是原输入图，按优先级reshape

mapp = np.zeros((32,5,5), dtype=np.int16)#8通道，14行14列
mapp = np.transpose(IFM, (2, 0, 1))#调整轴的顺序为通道、行、列
            
count = 0
for i in range(5):
    for j in range(5):
        for k in range(32):
            if mapp[k][i][j] == 0:
                count = count + 1
            
print('原输入特征图：')
print(mapp)

print('稀疏度：')
print(count/(5*5*32))

data = []
for channel in range(0,32):  # 遍历每个通道
    channel_data = mapp[channel]  # 获取当前通道的数据
    channel_df = pd.DataFrame(channel_data)  # 转换为 DataFrame
    channel_df['Channel'] = f'Channel {channel + 1}'  # 添加通道标识列
    data.append(channel_df)

# 将所有通道的数据合并成一个大的 DataFrame
combined_df = pd.concat(data, ignore_index=True)

# 将 DataFrame 写入 Excel 文件
combined_df.to_excel('C:\\Users\\zuohaonan\\Desktop\\PE3\\NN_accelerator\\outputp.xlsx', index=False)

kernel_convert = list(map(trans, kernel))
ker = np.zeros((32,288), dtype=np.int16)

Core = [np.zeros((32,3,3), dtype=int) for _ in range(32)]
kernel_re = [np.zeros((3,3,32), dtype=int) for _ in range(32)]

bias_convert = list(map(trans40, bias))
print('偏置:')
print(bias_convert)

for i in range(0,32):
    for j in range(0,288):
        ker[i][j] = kernel_convert[j + 288 * i]
        
for k in range(0,32):
    kernel_re[k] = ker[k].reshape(3,3,32)#行、列、通道
    Core[k] = np.transpose(kernel_re[k], (2, 0, 1))#调整轴的顺序为通道、行、列
    print(f"这是第{k}个卷积核:")
    print(Core[k])

post_MAC = [np.zeros((3, 3), dtype=int) for _ in range(32)]
mem = [np.zeros((3, 3), dtype=int) for _ in range(32)]
OFM = np.zeros(32, dtype=int)

def conv(row_loc,col_loc,num):
    result = 0
    for i in range(0,3):
        for j in range(0,3):
            for k in range(0,32):
                result += (Core[num])[k][i][j]*mapp[k][row_loc+i][col_loc+j]

    mem[num][row_loc][col_loc] = result
    result += int(bias_convert[num])

    if result < 0:
        result = 0
            
    return result

def cut(dacc,bit):

    mask= (1 << (26-bit)) - 1  # 0b11111111111111111111111111
    
    temp_bits = (dacc>> (bit+15)) & mask#获取27-40位
    dacc_40 = (dacc >> 40) & 1#获取最高位
    dacc_li = (dacc>>bit) & ((1 << 15) - 1)#获取0-14位

    if temp_bits == 0 or temp_bits == (1 << (26-bit)) - 1:
        dcut = (dacc_40 << 15) | dacc_li
    else:
        dcut = 0b1000000000000000 if dacc_40 else 0b0111111111111111
    return (binary_to_decimal(dcut))

def max(a, b, c, d, e, f, g, h, i):
    if a >= b:
        t1 = a
    else:
        t1 = b

    if c >= d:
        t2 = c
    else:
        t2 = d

    if t1 >= t2:
        max1 = t1
    else:
        max1 = t2

    if e >= f:
        t3 = e
    else:
        t3 = f

    if g >= h:
        t4 = g
    else:
        t4 = h

    if t3 >= t4:
        max2 = t3
    else:
        max2 = t4

    if max1 >= max2:
        max3 = max1
    else:
        max3 = max2

    if max3 >= i:
        return max3
    else:
        return i
        
def pool(row_loc,col_loc,num):
      
    result = max((post_MAC[num])[3*row_loc][3*col_loc],(post_MAC[num])[3*row_loc+1][3*col_loc],(post_MAC[num])[3*row_loc][3*col_loc+1],(post_MAC[num])[3*row_loc+1][3*col_loc+1],(post_MAC[num])[3*row_loc+1][3*col_loc+2],(post_MAC[num])[3*row_loc+2][3*col_loc+1],(post_MAC[num])[3*row_loc][3*col_loc+2],(post_MAC[num])[3*row_loc+2][3*col_loc],(post_MAC[num])[3*row_loc+2][3*col_loc+2])
    return result

for i in range(0,3):
    for j in range(0,3):
        for k in range(0,32):
            temp = conv(i,j,k)
            post_MAC[k][i][j] = cut(int(temp),0)

for k in range(0,32):
    print(f'这是第{k}张中间结果')
    print(mem[k])
    print('\n')


for k in range(0,32):
    OFM[k]= pool(0,0,k)

all_values = np.concatenate([arr.flatten() for arr in OFM])
non_zero_values = all_values[all_values != 0]  # 过滤非零值

# 计算统计值（包括全体的最大值和最小值）
max_value = np.max(all_values)  # 包含零的最大值
min_value = np.min(all_values)  # 包含零的最小值

# 计算非零值的平均值和中位数
if len(non_zero_values) > 0:
    mean_non_zero = np.mean(non_zero_values)
    median_non_zero = np.median(non_zero_values)
else:
    mean_non_zero = 0  # 如果无非零值，默认输出0
    median_non_zero = 0

# 输出结果
print(f"最大值（含零）: {max_value}")
print(f"最小值（含零）: {min_value}")
print(f"非零值的平均值: {mean_non_zero}")
print(f"非零值的中位数: {median_non_zero}")
limit = round(mean_non_zero/16)

with open('C:\\Users\\zuohaonan\\Desktop\\PE3\\NN_accelerator\\ofm_data03.txt', 'w') as file:
    print(f'这是输出向量')
    print(OFM)
    print('\n')
    for k in range(0,32):
        if OFM[k] < 0:
            value = OFM[k] + 65536
        else:
            value = OFM[k]
            
        hex_value = format(value, '04X')
        file.write(hex_value + '\n')
        

with h5py.File('C:\\Users\\zuohaonan\\Desktop\\PE3\\NN_accelerator\\resultl3t.h5', 'w') as hf:
    # 初始化result1数据集（1568个UTF-8编码的16位字符串）
    result1 = hf.create_dataset("result", 
                               shape=(32,), 
                               dtype=h5py.string_dtype(encoding='utf-8', length=16))  # UTF-8固定长度16字节
    
    index = 0  # 写入位置索引
    
    # 遍历OFM并填充result1
    

    for k in range(32):
        # 处理负数（转换为补码形式的正数）
        value = OFM[k]
        if value > limit + 1:
            value = int(value/limit)  # 16位补码转换
                
        # 转换为16位二进制字符串（UTF-8格式）
        binary_str = format(value, '016b')  # 如 "0000000000000000"
        result1[index] = binary_str
        index += 1

print("已写入完毕")

原输入特征图：
[[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  6]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 8 18 10 18 33]
  [14 22 21 12  2]
  [10 16 14 23  8]
  [17 11 25  4  4]
  [26 17 30 30 43]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  4  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0 25  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  8  1  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  1]
  [ 0  0  0  0  0]
  [ 0  0  0  0 18]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0 11  0  8]
  [25  2  7  0  0]
  [ 6 12  7  0  0]
  [12  0  7 21  8]
  [ 1 22 13  5  0]]

 [[ 0  0  0 25 12]
  [ 0  1  0  8  0]
  [ 3  0  4  0  0]
  [16  6  7 29 32]
  [11 10  0  0  0]]

 [[ 0  0  2  0  8]
  [